/**
 * Alert schemas.
 *
 * Nobody creates alerts from the interface: they are generated by the
 * scheduled jobs (forecast overdraft, consent about to expire, a direct debit
 * that has not arrived...). From here they can only be read and dismissed,
 * and that is why the only thing to validate are the list filters.
 */

import { z } from "zod/v4";

export const alertFiltersSchema = z.object({
  /** By default dismissed ones are hidden: dismissing one means «out». */
  descartats: z
    .union([z.literal("1"), z.literal("true"), z.literal("on")])
    .optional()
    .transform((v) => v !== undefined),
  limit: z.coerce.number().int().min(1).max(200).default(50),
});

export type AlertFilters = z.infer<typeof alertFiltersSchema>;

/** Rebuilds the canonical query string, for `HX-Push-Url`. */
export function alertFiltersToQuery(filters: AlertFilters): string {
  const params = new URLSearchParams();
  if (filters.descartats) params.set("descartats", "1");
  if (filters.limit !== 50) params.set("limit", String(filters.limit));
  const q = params.toString();
  return q ? `?${q}` : "";
}
