"""esquema inicial

Revision ID: bf934a3d946b
Revises:
Create Date: 2026-08-25 15:58:00.978281
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "bf934a3d946b"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "categories",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("parent_id", sa.Integer(), nullable=True),
        sa.Column("slug", sa.String(length=80), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column(
            "kind",
            sa.Enum(
                "income", "expense", "transfer", name="categorykind", native_enum=False, length=32
            ),
            nullable=False,
        ),
        sa.Column("color", sa.String(length=9), nullable=False),
        sa.Column("icon", sa.String(length=40), nullable=False),
        sa.Column("is_system", sa.Boolean(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["categories.id"],
            name=op.f("fk_categories_parent_id_categories"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_categories")),
        sa.UniqueConstraint("slug", name=op.f("uq_categories_slug")),
    )
    op.create_index(op.f("ix_categories_parent_id"), "categories", ["parent_id"], unique=False)
    op.create_table(
        "ledgers",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("code", sa.String(length=50), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("color", sa.String(length=9), nullable=False),
        sa.Column("overdraft_threshold", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ledgers")),
        sa.UniqueConstraint("code", name=op.f("uq_ledgers_code")),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("full_name", sa.String(length=255), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("is_admin", sa.Boolean(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_table(
        "alerts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("ledger_id", sa.Integer(), nullable=True),
        sa.Column(
            "type",
            sa.Enum(
                "projected_overdraft",
                "consent_expiring",
                "consent_expired",
                "recurring_amount_change",
                "recurring_missing",
                "sync_failed",
                name="alerttype",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "severity",
            sa.Enum(
                "info", "warning", "critical", name="alertseverity", native_enum=False, length=32
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum("new", "read", "dismissed", name="alertstatus", native_enum=False, length=32),
            nullable=False,
        ),
        sa.Column("dedup_key", sa.String(length=200), nullable=False),
        sa.Column("title", sa.String(length=250), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("notified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["ledger_id"],
            ["ledgers.id"],
            name=op.f("fk_alerts_ledger_id_ledgers"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_alerts")),
        sa.UniqueConstraint("dedup_key", name="uq_alert_dedup_key"),
    )
    op.create_index(op.f("ix_alerts_ledger_id"), "alerts", ["ledger_id"], unique=False)
    op.create_index(op.f("ix_alerts_status"), "alerts", ["status"], unique=False)
    op.create_index(op.f("ix_alerts_type"), "alerts", ["type"], unique=False)
    op.create_table(
        "bank_connections",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("aspsp_name", sa.String(length=120), nullable=False),
        sa.Column("aspsp_country", sa.String(length=2), nullable=False),
        sa.Column("psu_type", sa.String(length=20), nullable=False),
        sa.Column("eb_session_id", sa.String(length=128), nullable=True),
        sa.Column("eb_auth_state", sa.String(length=128), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "active",
                "expired",
                "revoked",
                "error",
                name="connectionstatus",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("valid_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_sync_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=False),
        sa.Column("created_by_id", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["users.id"],
            name=op.f("fk_bank_connections_created_by_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_bank_connections")),
        sa.UniqueConstraint("eb_session_id", name=op.f("uq_bank_connections_eb_session_id")),
    )
    op.create_index(
        op.f("ix_bank_connections_eb_auth_state"),
        "bank_connections",
        ["eb_auth_state"],
        unique=False,
    )
    op.create_table(
        "merchants",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("normalized_name", sa.String(length=200), nullable=False),
        sa.Column("display_name", sa.String(length=200), nullable=False),
        sa.Column("default_category_id", sa.Integer(), nullable=True),
        sa.Column(
            "category_source",
            sa.Enum(
                "none",
                "merchant",
                "rule",
                "llm",
                "user",
                name="categorysource",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("is_confirmed", sa.Boolean(), nullable=False),
        sa.Column("transaction_count", sa.Integer(), nullable=False),
        sa.Column("last_seen_at", sa.Date(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["default_category_id"],
            ["categories.id"],
            name=op.f("fk_merchants_default_category_id_categories"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_merchants")),
        sa.UniqueConstraint("normalized_name", name=op.f("uq_merchants_normalized_name")),
    )
    op.create_index(
        op.f("ix_merchants_default_category_id"), "merchants", ["default_category_id"], unique=False
    )
    op.create_table(
        "user_ledger_permissions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("ledger_id", sa.Integer(), nullable=False),
        sa.Column(
            "role",
            sa.Enum("viewer", "editor", "admin", name="ledgerrole", native_enum=False, length=32),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["ledger_id"],
            ["ledgers.id"],
            name=op.f("fk_user_ledger_permissions_ledger_id_ledgers"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_user_ledger_permissions_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_ledger_permissions")),
        sa.UniqueConstraint("user_id", "ledger_id", name="uq_user_ledger"),
    )
    op.create_index(
        op.f("ix_user_ledger_permissions_ledger_id"),
        "user_ledger_permissions",
        ["ledger_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_user_ledger_permissions_user_id"),
        "user_ledger_permissions",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "user_sessions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("user_agent", sa.String(length=255), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_user_sessions_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_sessions")),
    )
    op.create_index(
        op.f("ix_user_sessions_token_hash"), "user_sessions", ["token_hash"], unique=True
    )
    op.create_index(op.f("ix_user_sessions_user_id"), "user_sessions", ["user_id"], unique=False)
    op.create_table(
        "accounts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("connection_id", sa.Integer(), nullable=False),
        sa.Column("ledger_id", sa.Integer(), nullable=True),
        sa.Column("eb_account_uid", sa.String(length=128), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("product", sa.String(length=120), nullable=False),
        sa.Column("iban", sa.String(length=34), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("cash_account_type", sa.String(length=20), nullable=False),
        sa.Column("usage", sa.String(length=20), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("history_start_date", sa.Date(), nullable=True),
        sa.Column("last_booked_date", sa.Date(), nullable=True),
        sa.Column("raw", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["connection_id"],
            ["bank_connections.id"],
            name=op.f("fk_accounts_connection_id_bank_connections"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["ledger_id"],
            ["ledgers.id"],
            name=op.f("fk_accounts_ledger_id_ledgers"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_accounts")),
        sa.UniqueConstraint("eb_account_uid", name=op.f("uq_accounts_eb_account_uid")),
    )
    op.create_index(op.f("ix_accounts_connection_id"), "accounts", ["connection_id"], unique=False)
    op.create_index(op.f("ix_accounts_ledger_id"), "accounts", ["ledger_id"], unique=False)
    op.create_table(
        "llm_suggestions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("merchant_id", sa.Integer(), nullable=True),
        sa.Column("model", sa.String(length=80), nullable=False),
        sa.Column("prompt_version", sa.String(length=20), nullable=False),
        sa.Column("input_text", sa.Text(), nullable=False),
        sa.Column("suggested_category_id", sa.Integer(), nullable=True),
        sa.Column("suggested_display_name", sa.String(length=200), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column("rationale", sa.Text(), nullable=False),
        sa.Column("accepted", sa.Boolean(), nullable=True),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["merchant_id"],
            ["merchants.id"],
            name=op.f("fk_llm_suggestions_merchant_id_merchants"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["suggested_category_id"],
            ["categories.id"],
            name=op.f("fk_llm_suggestions_suggested_category_id_categories"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_llm_suggestions")),
    )
    op.create_index(
        op.f("ix_llm_suggestions_merchant_id"), "llm_suggestions", ["merchant_id"], unique=False
    )
    op.create_table(
        "recurring_series",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("ledger_id", sa.Integer(), nullable=False),
        sa.Column("signature", sa.String(length=220), nullable=False),
        sa.Column("label", sa.String(length=200), nullable=False),
        sa.Column("merchant_id", sa.Integer(), nullable=True),
        sa.Column("category_id", sa.Integer(), nullable=True),
        sa.Column(
            "cadence",
            sa.Enum(
                "weekly",
                "biweekly",
                "monthly",
                "bimonthly",
                "quarterly",
                "semiannual",
                "annual",
                name="cadence",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("expected_amount", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("amount_tolerance", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("interval_days", sa.Integer(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("occurrences_count", sa.Integer(), nullable=False),
        sa.Column("first_seen_date", sa.Date(), nullable=False),
        sa.Column("last_seen_date", sa.Date(), nullable=False),
        sa.Column("next_expected_date", sa.Date(), nullable=True),
        sa.Column("is_subscription", sa.Boolean(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("active", "ended", name="seriesstatus", native_enum=False, length=32),
            nullable=False,
        ),
        sa.Column("include_in_forecast", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["categories.id"],
            name=op.f("fk_recurring_series_category_id_categories"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["ledger_id"],
            ["ledgers.id"],
            name=op.f("fk_recurring_series_ledger_id_ledgers"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["merchant_id"],
            ["merchants.id"],
            name=op.f("fk_recurring_series_merchant_id_merchants"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_recurring_series")),
        sa.UniqueConstraint("ledger_id", "signature", name="uq_recurring_ledger_signature"),
    )
    op.create_index(
        op.f("ix_recurring_series_ledger_id"), "recurring_series", ["ledger_id"], unique=False
    )
    op.create_index(
        op.f("ix_recurring_series_next_expected_date"),
        "recurring_series",
        ["next_expected_date"],
        unique=False,
    )
    op.create_table(
        "rules",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("ledger_id", sa.Integer(), nullable=True),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("conditions", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("set_category_id", sa.Integer(), nullable=True),
        sa.Column("set_merchant_id", sa.Integer(), nullable=True),
        sa.Column("set_tags", postgresql.ARRAY(sa.String(length=40)), nullable=False),
        sa.Column(
            "source",
            sa.Enum("user", "learned", name="rulesource", native_enum=False, length=32),
            nullable=False,
        ),
        sa.Column("created_by_id", sa.Integer(), nullable=True),
        sa.Column("match_count", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["users.id"],
            name=op.f("fk_rules_created_by_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["ledger_id"],
            ["ledgers.id"],
            name=op.f("fk_rules_ledger_id_ledgers"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["set_category_id"],
            ["categories.id"],
            name=op.f("fk_rules_set_category_id_categories"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["set_merchant_id"],
            ["merchants.id"],
            name=op.f("fk_rules_set_merchant_id_merchants"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_rules")),
    )
    op.create_index(op.f("ix_rules_ledger_id"), "rules", ["ledger_id"], unique=False)
    op.create_table(
        "sync_runs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("connection_id", sa.Integer(), nullable=False),
        sa.Column(
            "trigger",
            sa.Enum(
                "scheduled", "manual", "initial", name="synctrigger", native_enum=False, length=32
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "running",
                "success",
                "partial",
                "failed",
                name="syncstatus",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("accounts_synced", sa.Integer(), nullable=False),
        sa.Column("transactions_inserted", sa.Integer(), nullable=False),
        sa.Column("transactions_updated", sa.Integer(), nullable=False),
        sa.Column("error", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["connection_id"],
            ["bank_connections.id"],
            name=op.f("fk_sync_runs_connection_id_bank_connections"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sync_runs")),
    )
    op.create_index(
        op.f("ix_sync_runs_connection_id"), "sync_runs", ["connection_id"], unique=False
    )
    op.create_index(op.f("ix_sync_runs_started_at"), "sync_runs", ["started_at"], unique=False)
    op.create_table(
        "balances",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("account_id", sa.Integer(), nullable=False),
        sa.Column("balance_type", sa.String(length=40), nullable=False),
        sa.Column("amount", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("reference_date", sa.Date(), nullable=False),
        sa.Column("fetched_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["accounts.id"],
            name=op.f("fk_balances_account_id_accounts"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_balances")),
        sa.UniqueConstraint(
            "account_id", "balance_type", "reference_date", name="uq_balance_account_type_date"
        ),
    )
    op.create_index(op.f("ix_balances_account_id"), "balances", ["account_id"], unique=False)
    op.create_table(
        "transactions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("account_id", sa.Integer(), nullable=False),
        sa.Column("ledger_id", sa.Integer(), nullable=True),
        sa.Column("entry_reference", sa.String(length=128), nullable=True),
        sa.Column("transaction_id", sa.String(length=128), nullable=True),
        sa.Column("dedup_key", sa.String(length=64), nullable=False),
        sa.Column(
            "source",
            sa.Enum(
                "enablebanking", "manual", name="transactionsource", native_enum=False, length=32
            ),
            nullable=False,
        ),
        sa.Column("booking_date", sa.Date(), nullable=False),
        sa.Column("value_date", sa.Date(), nullable=True),
        sa.Column("amount", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column(
            "status",
            sa.Enum("booked", "pending", name="transactionstatus", native_enum=False, length=32),
            nullable=False,
        ),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("normalized_description", sa.String(length=200), nullable=False),
        sa.Column("counterparty", sa.String(length=200), nullable=False),
        sa.Column("bank_transaction_code", sa.String(length=60), nullable=False),
        sa.Column("merchant_id", sa.Integer(), nullable=True),
        sa.Column("category_id", sa.Integer(), nullable=True),
        sa.Column(
            "category_source",
            sa.Enum(
                "none",
                "merchant",
                "rule",
                "llm",
                "user",
                name="categorysource",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("category_confidence", sa.Float(), nullable=True),
        sa.Column("needs_review", sa.Boolean(), nullable=False),
        sa.Column("applied_rule_id", sa.Integer(), nullable=True),
        sa.Column("transfer_group_id", sa.String(length=64), nullable=True),
        sa.Column("notes", sa.Text(), nullable=False),
        sa.Column("tags", postgresql.ARRAY(sa.String(length=40)), nullable=False),
        sa.Column("is_excluded", sa.Boolean(), nullable=False),
        sa.Column("raw", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["accounts.id"],
            name=op.f("fk_transactions_account_id_accounts"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["applied_rule_id"],
            ["rules.id"],
            name=op.f("fk_transactions_applied_rule_id_rules"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["categories.id"],
            name=op.f("fk_transactions_category_id_categories"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["ledger_id"],
            ["ledgers.id"],
            name=op.f("fk_transactions_ledger_id_ledgers"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["merchant_id"],
            ["merchants.id"],
            name=op.f("fk_transactions_merchant_id_merchants"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_transactions")),
        sa.UniqueConstraint("account_id", "dedup_key", name="uq_transaction_account_dedup"),
    )
    op.create_index(
        op.f("ix_transactions_account_id"), "transactions", ["account_id"], unique=False
    )
    op.create_index(
        op.f("ix_transactions_booking_date"), "transactions", ["booking_date"], unique=False
    )
    op.create_index(
        op.f("ix_transactions_category_id"), "transactions", ["category_id"], unique=False
    )
    op.create_index(
        "ix_transactions_ledger_booking",
        "transactions",
        ["ledger_id", "booking_date"],
        unique=False,
    )
    op.create_index(op.f("ix_transactions_ledger_id"), "transactions", ["ledger_id"], unique=False)
    op.create_index(
        op.f("ix_transactions_merchant_id"), "transactions", ["merchant_id"], unique=False
    )
    op.create_index(
        "ix_transactions_review", "transactions", ["needs_review", "ledger_id"], unique=False
    )
    op.create_index(
        op.f("ix_transactions_transfer_group_id"),
        "transactions",
        ["transfer_group_id"],
        unique=False,
    )
    op.create_table(
        "recurring_occurrences",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("series_id", sa.Integer(), nullable=False),
        sa.Column("transaction_id", sa.Integer(), nullable=False),
        sa.Column("occurred_on", sa.Date(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.ForeignKeyConstraint(
            ["series_id"],
            ["recurring_series.id"],
            name=op.f("fk_recurring_occurrences_series_id_recurring_series"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["transaction_id"],
            ["transactions.id"],
            name=op.f("fk_recurring_occurrences_transaction_id_transactions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_recurring_occurrences")),
        sa.UniqueConstraint("series_id", "transaction_id", name="uq_occurrence_series_transaction"),
    )
    op.create_index(
        op.f("ix_recurring_occurrences_series_id"),
        "recurring_occurrences",
        ["series_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_recurring_occurrences_transaction_id"),
        "recurring_occurrences",
        ["transaction_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_recurring_occurrences_transaction_id"), table_name="recurring_occurrences"
    )
    op.drop_index(op.f("ix_recurring_occurrences_series_id"), table_name="recurring_occurrences")
    op.drop_table("recurring_occurrences")
    op.drop_index(op.f("ix_transactions_transfer_group_id"), table_name="transactions")
    op.drop_index("ix_transactions_review", table_name="transactions")
    op.drop_index(op.f("ix_transactions_merchant_id"), table_name="transactions")
    op.drop_index(op.f("ix_transactions_ledger_id"), table_name="transactions")
    op.drop_index("ix_transactions_ledger_booking", table_name="transactions")
    op.drop_index(op.f("ix_transactions_category_id"), table_name="transactions")
    op.drop_index(op.f("ix_transactions_booking_date"), table_name="transactions")
    op.drop_index(op.f("ix_transactions_account_id"), table_name="transactions")
    op.drop_table("transactions")
    op.drop_index(op.f("ix_balances_account_id"), table_name="balances")
    op.drop_table("balances")
    op.drop_index(op.f("ix_sync_runs_started_at"), table_name="sync_runs")
    op.drop_index(op.f("ix_sync_runs_connection_id"), table_name="sync_runs")
    op.drop_table("sync_runs")
    op.drop_index(op.f("ix_rules_ledger_id"), table_name="rules")
    op.drop_table("rules")
    op.drop_index(op.f("ix_recurring_series_next_expected_date"), table_name="recurring_series")
    op.drop_index(op.f("ix_recurring_series_ledger_id"), table_name="recurring_series")
    op.drop_table("recurring_series")
    op.drop_index(op.f("ix_llm_suggestions_merchant_id"), table_name="llm_suggestions")
    op.drop_table("llm_suggestions")
    op.drop_index(op.f("ix_accounts_ledger_id"), table_name="accounts")
    op.drop_index(op.f("ix_accounts_connection_id"), table_name="accounts")
    op.drop_table("accounts")
    op.drop_index(op.f("ix_user_sessions_user_id"), table_name="user_sessions")
    op.drop_index(op.f("ix_user_sessions_token_hash"), table_name="user_sessions")
    op.drop_table("user_sessions")
    op.drop_index(op.f("ix_user_ledger_permissions_user_id"), table_name="user_ledger_permissions")
    op.drop_index(
        op.f("ix_user_ledger_permissions_ledger_id"), table_name="user_ledger_permissions"
    )
    op.drop_table("user_ledger_permissions")
    op.drop_index(op.f("ix_merchants_default_category_id"), table_name="merchants")
    op.drop_table("merchants")
    op.drop_index(op.f("ix_bank_connections_eb_auth_state"), table_name="bank_connections")
    op.drop_table("bank_connections")
    op.drop_index(op.f("ix_alerts_type"), table_name="alerts")
    op.drop_index(op.f("ix_alerts_status"), table_name="alerts")
    op.drop_index(op.f("ix_alerts_ledger_id"), table_name="alerts")
    op.drop_table("alerts")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_table("ledgers")
    op.drop_index(op.f("ix_categories_parent_id"), table_name="categories")
    op.drop_table("categories")
    # ### end Alembic commands ###
